apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-storage
spec:
  serviceName: svc-storage
  replicas: 1
  selector:
    matchLabels:
      app: api-gw
  template:
    metadata:
      labels:
        app: api-gw
    spec:
      containers:
        - name: storage
          image: $IMAGE_NAME_STORE:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
